Revert "[TECH] Exclure le schéma pgboss du dump de la réplication."
1024pix/pix-db-replication pull request #115
Opened 2022-07-05 08:10 UTC by francois2metz

This reverts commit 77196086befefb992b23edc8a31e483c577319de, reversing
changes made to acc11d0edb8e8f63c8c1557c629da68717cb57da.

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-07-05 13:31 UTC, mickaelalibert approved these changes

2022-07-05 13:36 UTC, yahyayouness requested changes
A quoi ca sert de répliquer le schéma pgboss actuellement. Au risque de rallonger le temps de réplication de données ?
J'avais voulu rajouter les droits nécessaires mais ca servait à rien de répliquer ces données actuellement car on on s'en sert pas pour le moment. Pgboss n'est pas en production encore.
J'avais demandé à Arthur de monter un point pour qu'on puisse discuter des données à répliquer de ce schéma Jboss, mais ca sera fait dans un second temps si besoin.

2022-07-05 13:39 UTC, yahyayouness reviewed
Peux tu enrichir stp la partie test ? et les temps de réponses obtenues suite à ce rajout de dump avec pgboss ?

2022-07-05 13:40 UTC, yahyayouness reviewed
A quoi ca sert de dump pgboss alors qu'on ne l'utilise pas encore ?

2022-07-06 16:23 UTC, yahyayouness commented
Une des tables de pgboss contient des archives avec deux colonnes en jsonb qui peuvent être volumineuses. 

<img width="893" alt="Capture d’écran 2022-07-06 à 18 19 42" src="https://user-images.githubusercontent.com/10045497/177597855-0cf30174-1d1b-468d-843c-d3942156f8aa.png">

2022-10-10 08:51 UTC, octo-topi commented
Exécution des requêtes sur `pix-api-intégration`
``` sql
GRANT SELECT ON ALL TABLES IN SCHEMA pgboss TO replication;
GRANT USAGE ON SCHEMA pgboss TO replication;
```

2022-10-10 09:23 UTC, octo-topi commented
Func review OK
``
scalingo --region osc-fr1 --app pix-datawarehouse-integration-pr115 logs  --lines 10000 | grep pgboss
2022-10-10 11:08:41.361082016 +0200 CEST [background-1] pg_restore: creating SCHEMA "pgboss"
2022-10-10 11:08:41.383784765 +0200 CEST [background-1] pg_restore: creating TABLE "pgboss.version"
2022-10-10 11:08:41.380257668 +0200 CEST [background-1] pg_restore: creating TABLE "pgboss.subscription"
2022-10-10 11:08:41.376032085 +0200 CEST [background-1] pg_restore: creating TABLE "pgboss.schedule"
2022-10-10 11:08:41.371914260 +0200 CEST [background-1] pg_restore: creating TABLE "pgboss.job"
2022-10-10 11:08:41.365131153 +0200 CEST [background-1] pg_restore: creating TABLE "pgboss.archive"
2022-10-10 11:08:41.363459811 +0200 CEST [background-1] pg_restore: creating TYPE "pgboss.job_state"
```

2022-10-10 09:27 UTC, octo-topi approved these changes

2022-10-10 10:31 UTC, francois2metz commented
Est-ce qu'on peut enlever les instructions du README relatives aux RA qui sont en doublons avec le reste des instructions de production ?

2022-10-10 12:04 UTC, merged

2022-10-10 12:04 UTC, francois2metz commented
Avant la mise en prod il faudra bien rajouter les droits sur la prod.

2022-10-10 13:54 UTC, mickaelalibert commented
> Avant la mise en prod il faudra bien rajouter les droits sur la prod.

Done ✅