[TECH] Dump complet de la base de données et envoie sur un bucket S3 (PIX-8344)
1024pix/pix-db-replication pull request #196
Opened 2023-08-18 12:41 UTC by emeric-martineau

## :unicorn: Problème
La sauvegarde de base de données se fait uniquement via l'hébergeur.

## :robot: Solution
Dumper la base et copier le dump sur un bucket S3

## :rainbow: Remarques
Avoir un hébergement avec un bucket S3

## :100: Pour tester
Pour tester, il faut impérativement lancer le docker compose qui met à disposition une base PostgreSQL et Minio (un S3 compatible)

2023-08-28 08:32 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +'use strict';
**nitpick**
Renommer le fichier en `dump-and-push-on-S3`

2023-08-28 08:34 UTC, octo-topi commented on sample.env
> +
```suggestion
#######################
### Envoi dump vers S3  ##
#######################
```

2023-08-28 08:35 UTC, octo-topi commented on sample.env
> +# Définit l'access key pour uploader le dump de la base
```suggestion
# Access key du bucket S3
```

2023-08-28 08:36 UTC, octo-topi commented on sample.env
> +# sur le bucket S3
```suggestion
# Access key du bucket S3
```

2023-08-28 08:36 UTC, octo-topi commented on sample.env
> +# sur le bucket S3
```suggestion
# Secret access key du bucket S3
```
```

2023-08-28 08:37 UTC, octo-topi commented on sample.env
> +# Définit le endpoint de l'API S3 (ex: https://s3.gra.io.cloud.ovh.net)
```suggestion
# Endpoint du bucket S3
```

2023-08-28 08:37 UTC, octo-topi commented on sample.env
> +# default : ''
```suggestion
# sample:  https://s3.gra.io.cloud.ovh.net
# default : ''
```

2023-08-28 08:38 UTC, octo-topi commented on sample.env
> +# default : ''
C'est plus clair de dire qu'il n'y en a pas
```suggestion
# default : none
```

2023-08-28 08:38 UTC, octo-topi commented on src/main.js
> +const dumpAndPushS3Queue = _createQueue('Notification queue');
**nitpick**
```suggestion
const dumpAndPushtoS3UploadQueue = _createQueue('Notification queue');
```

2023-08-28 08:40 UTC, octo-topi requested changes
Les commit ne passent pas isolément (notamment `Fix lint`).
Tu peux les squasher au pire des cas.

2023-08-28 08:42 UTC, octo-topi commented on src/main.js
> +    notificationQueue.add({}, { ...jobOptions, attempts: 1 });
Comme le S3 est en dehors du réseau, je propose de configurer le nombre de tentatives via une variable d'environnement
```suggestion
    notificationQueue.add({}, { ...jobOptions, attempts });
```

2023-08-28 08:42 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +function createS3(configuration) {
**nitpick**
```suggestion
function createS3Client(configuration) {
```

2023-08-28 08:44 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +  logger.info('Start upload dump database to S3');
```suggestion
  logger.info('Uploadjng dump to S3 bucket..');
```

2023-08-28 08:45 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +  logger.info('End upload dump database to S3');
**nitpick**
```suggestion
  logger.info('Dump successfully uploaded');
```

2023-08-28 08:46 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +    Key: `${configuration.S3_OBJECT_NAME_PREFIX}-${currentDate}`,
**nitpick**
const objectName = `${configuration.S3_OBJECT_NAME_PREFIX}-${currentDate}`;

```suggestion

  await s3.upload({
    Bucket: configuration.S3_BUCKET_NAME,
    Key: objectName,
```

2023-08-28 09:40 UTC, octo-topi commented on test/acceptance/dump_and_push_on_s3_test.js
> +    it('sould create dump', async () => {
```suggestion
    it('should create dump', async () => {
```

2023-08-28 10:17 UTC, octo-topi commented
Rajouter dans le README l'exécution one-shot
```
``` bash
node -e "require('./src/steps/dump_and_push_on_s3').run(require ('./src/config/extract-configuration-from-environment')())"
```

2023-08-28 10:18 UTC, octo-topi commented on src/steps/backup-restore/index.js
> +async function createBackup(configuration, tablesToExcludeFromBackup) {
C'est le moment d'aider le développeur qui va rajouter un argument après
```suggestion
async function createBackup({configuration, tablesToExcludeFromBackup}) {
```

2023-08-28 10:24 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +    sslEnabled: !(process.env.NODE_ENV === 'test'),
Alimenter cette variable avec false dans le fichier `src/config/extract-configuration-from-environment.js` si `NODE_ENV=test` comme sur le monorepo
https://github.com/1024pix/pix/blob/dev/api/lib/config.js#L341

```suggestion
    // eslint-disable-next-line no-process-env
    sslEnabled: configuration.s3Backup.sslEnabled
```

2023-08-28 10:27 UTC, octo-topi commented on src/config/extract-configuration-from-environment.js
> +    S3_OBJECT_NAME_PREFIX: process.env.S3_OBJECT_NAME_PREFIX,
Grouper les variables, ce qui permet de supprimer le préfixe.
Les nommer en camelCase comme sur le monorepo
https://github.com/1024pix/pix/blob/dev/api/lib/config.js

```suggestion
    backupToS3: {
	    accessKey: process.env.S3_ACCESS_KEY,
	    secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
	    endpoint: process.env.S3_ENDPOINT,
	    regionName: process.env.S3_REGION,
	    bucketName: process.env.S3_BUCKET_NAME,
	    objectNamePrefix: process.env.S3_OBJECT_NAME_PREFIX
    },
```

2023-08-28 10:30 UTC, octo-topi commented on src/steps/dump_and_push_on_s3.js
> +  const blob = fs.readFileSync(dumpFilename);
Pourquoi utiliser une fonction bloquante ?
Il y a une version non-bloquante
https://nodejs.org/api/fs.html

2023-08-28 10:33 UTC, octo-topi commented on package.json
> +    "aws-sdk": "^2.1438.0",
On utilise la dépendance `@aws-sdk/client-s3` sur le monorepo.
Quelle est l'avantage d'utiliser la dépendance `aws-sdk` ? 

https://github.com/1024pix/pix/blob/tech-improve-api-structure-adr/api/lib/infrastructure/external-storage/s3-utils.js

2023-08-29 09:57 UTC, emeric-martineau commented on src/steps/dump_and_push_on_s3.js
> +  const blob = fs.readFileSync(dumpFilename);
Ah, oui, l'habitude

2023-08-29 13:44 UTC, emeric-martineau commented on package.json
> +    "aws-sdk": "^2.1438.0",
fait

2023-08-29 13:45 UTC, emeric-martineau commented on src/steps/dump_and_push_on_s3.js
> +    sslEnabled: !(process.env.NODE_ENV === 'test'),
modifié

2023-08-29 13:45 UTC, emeric-martineau commented on src/steps/backup-restore/index.js
> +async function createBackup(configuration, tablesToExcludeFromBackup) {
mis à jour

2023-09-04 08:07 UTC, mickaelalibert commented
On laisse la PR pour avoir le code, mais on rediscutera de notre stratégie désirée avant de continuer à avancer sur le sujet

2023-09-04 08:07 UTC, closed without merging